import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'Language': 'ಭಾಷೆ ಬದಲಿಸಿ',
      'title': 'Login',
      'email': 'Email',
      'password': 'Password',
      'login': 'Login',
      'select_language': 'Select Language',
      'profile_name': 'Profile',
      'dashboard': 'Home',
      'settings': 'Settings',
      'chat': 'Chat',
      'profile': 'My Profile',
      'shortlist': 'Shortlisted',
      'loggedInMember': 'Recently Logged In Members',
      'matchedProfile': ' Matched Profiles ',
      'recentlyJoined': 'Recently Joined',
      'plans': 'Membership Plan',
      'profileStatus': 'Profile Status',
      'logout': 'Log Out',
      'search': 'Search',
      'matches': 'My Connections',
      'terms': 'Terms & Conditions',
      'name': 'Name',
      "first_name": "First Name",
      "last_name": "Last Name",
      "gender_male": "Male",
      "gender_female": "Female",
      "dob": "Date of Birth",
      "age": "Age",
      "gender": "Gender",
      'phone_number': 'Phone Number',
      "sub_caste": "Sub Caste",
      "marital_status": "Marital Status",
      "creator_name": "Creator Name",
      "creator_phone": "Creator Phone",
      "height": "Height (cm)",
      "weight": "Weight (kg)",
      "blood_group": "Blood Group",
      "complexion": "Complexion",
      "country": "Country",
      "state": "State",
      "city": "City",
      "address": "Address",
      "remarks": "Remarks",
      "qualification": "Qualification",
      "specialisation": "Specialisation",
      "profession": "Profession",
      "company_name": "Company Name",
      "company_city": "Company City",
      "salary_range": "Salary Range",
      "rashi": "Rashi",
      "nakshatra": "Nakshatra",
      "gothra": "Gothra/Bedagu",
      "birth_time": "Birth Time",
      "birth_place": "Birth Place",
      "place": "Place",
      "family_deity": "Family Deity",
      "no_of_kids": "Number of Kids",
      "father_name": "Father's Name",
      "father_occupation": "Father's Occupation",
      "mother_name": "Mother's Name",
      "mother_occupation": "Mother's Occupation",
      "no_of_brothers": "Number of Brothers",
      "no_of_sisters": "Number of Sisters",
      "mother_tongue": "Mother Tongue",
      "family_type": "Family Type",
      "reference_name": "Reference Name",
      "reference_phone": "Reference Phone Number",
      "next": "NEXT",
      "additional_details": "Additional Details",
      "horoscope": "Horoscope Details",
      "education_profession": "Education & Profession",
      "family_details": "Family Details",
      "permanent_address": "Permanent Address",
      "basic_details": "Basic Details",
      "images": "Photos",
      "disabilities": "Disability",
      "no_images": "No additional images found",
      "liked_by_me": "Liked by Me",
      "liked_by_others": "Liked by Others",
      "viewed_by_me": "Viewed by Me",
      "viewed_by_others": "Viewed by Others",
      "contacted": "I contacted",
      "mutually_liked": "Mutually Liked",
      "no_matches": "No matching profiles found",
      "submit": "Submit",
      "shortlisted": "Shortlisted",
      "no_profiles": "No profiles found",
      "category": "Category",
      "enter_id": "Enter Matri ID",
      "apply_filters": "Apply Filters",
      "age_range": "Age Range: {min} - {max} years",
      "height_range": "Height Range: {min} - {max} cm",
      "matri_id": "Matri ID",
      "education": "Education",
      'sign_up': 'Sign Up',
      'creating_profile_for': 'Creating Profile For',
      'your_name': 'Your Name',
      'get_otp': 'Generate OTP',
      'enter_otp': 'Enter OTP',
      'resend_otp': 'Resend OTP',
      'set_password': 'Set Password',
      'confirm_password': 'Confirm Password',
      'agree': 'I agree to the ',
      'terms_and_conditions': 'Terms and Conditions',
      'already_have_account': 'Already have an account?',
      "otp_resend": "Resend OTP in {seconds} seconds",
      "enter_personal_details": "Enter Your Personal Details",
      "enter_sons_details": "Enter Your Son's Details",
      "enter_daughters_details": "Enter Your Daughter's Details",
      "enter_brothers_details": "Enter Your Brother's Details",
      "enter_sisters_details": "Enter Your Sister's Details",
      "skip": "Skip and Continue",
      "additional_images": "Upload Additional Images",
      "main_image": "Upload Main Image",
      "partner_preference": "Partner Preference",
      "or": "or",
      "personal_info": "Personal Information",
      "contact_info": "Contact Info",
      "contact_details": "Contact Information",
      "block": "Block",
      "block_report": "Block or Report",
      "cancel": "Cancel",
      "not_available": "Not available",
      "basic": "Basic",
      "attributes": "Physical Attributes",
      "family": "Family",
      "profile_handler": "Profile Handler",
      "info": "Info",
      "report": "Report",
      "reason":"Enter your reason",
      "comment":"Comment",
      "like":"Like",
      "confirm_logout":"Confirm Logout",
      "confirm_text":"Are you sure you want to log out?",
      "login_otp":"Login with OTP",
      "login_other":"Login with Mobile Number, Matri ID",
      "forgot_password":"Forgot Password",
      "new_account":"Didn't have an account? Register Now",
      "query_support":"For any Query / Support Click here",
      "change_status":"Change Status",
      "send_otp":"Send OTP",
      "verify_otp":"Verify OTP",
      "confirm_deletion":"Confirm Account Deletion",
      "delete_dialog":"Are you sure you want to delete your profile?\nOnce deleted, your account cannot be recovered, and all data will be permanently lost.",
      "delete":"Delete",
      "active":"Active",
      "married":"Married",
      "not_interested":"Not Interested",
      "exit":"Exit",
      "confirm_exit":"Are you sure you want to Exit?",
      "no":"No",
      "no_products":"No products found",
      "buy":"Buy",
      "retry_purchase":"It seems you cancelled the purchase. Would you like to try again?",
      "buy_premium":"Buy Premium",
      "need_premium":"You need a Premium to access more profiles.",
      "subscribe_now":"Subscribe Now",
      "block_user":"The blocked user will no longer be able to view your profile.\n",
      "report_user":"The user will be reported to the admin for review. Strict action will be taken against any illegal or inappropriate behavior, and the user will no longer be able to view your profile.",
      "no_message":"No Message",
      "type_message":"Type a message....",
      "fill_info":"Please fill all required fields properly.",
      "ok":"OK",
      "reset_password":"Reset Password",
      "success":"Success",
      "failed":"Failed",
      "success_msg":"Ticket successfully added.",
      "failure_msg":"Could not submit the ticket.",
      "support":"Support",
      "issues":"Issues",
      "min_char":"(Min 10 characters)",
      "support_contact":"Support/Contact",
      "taralabalu":"Taralabalu Kendra",
      "phone":"Phone:",
      "tb_address":"Address: 2nd Block, 3rd Main Rd, Near B D A Complex,\nRT Nagar, Bengaluru, Karnataka 560032",
      "contact_us":"Contact Us",
      "upload_profile":"Upload Profile",
      "profile_msg":"Please update your profile picture.",
      "upload_now":"Upload Now",
      "login_validation":"Please enter Login Id and password.",
      "accept_terms":"Please accept the Terms and Conditions to proceed.",
      "no_internet":"No internet connection",
      "no_internet_msg":"Please check your network and try again.",
      "new_password":"New Password",
      "change_password":"Change Password",
      "choose":"Choose an option:",
      "set_profile":"Set as Profile Photo",
      "delete_photo":"Delete",
      "upload_one":"Please upload at least one image.",
      "no_chats":"No chats available",
      "profile_count":"Pending Profile View Count",
      "message_count":"Pending Message Count",
      "contact_count":"Pending Contact Count",
      "pending_counts":"Pending Counts"
    },
    'kn': {
      'Language': 'Change Language',
      'title': 'ಲಾಗಿನ್',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್‌ವರ್ಡ್',
      'login': 'ಲಾಗಿನ್',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'profile_name': 'ಪ್ರೊಫೈಲ್',
      'dashboard': 'ಹೋಮ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್',
      'chat': 'ಚಾಟ್',
      'profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'shortlist': 'ಕಿರುಪಟ್ಟಿ',
      'loggedInMember': 'ಇತ್ತೀಚಿನ ಲಾಗಿನ್ ಬಳಕೆದಾರರು',
      'matchedProfile': 'ಸೂಕ್ತವಾದ ಬಳಕೆದಾರರು',
      'recentlyJoined': 'ಇತ್ತೀಚೆಗೆ ಸೇರ್ಪಡೆಗೊಂಡವರು',
      'plans': 'ಮೆಂಬರ್‌ಶಿಪ್ ಪ್ಲಾನ್',
      'profileStatus': 'ಖಾತೆಯ ಸ್ಥಿತಿ',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'search': 'ಹುಡುಕಿ',
      'matches': 'ಸಂಪರ್ಕಗಳು',
      'terms': 'ನಿಯಮಗಳು ಮತ್ತು ಶರತ್ತುಗಳು',
      'name': 'ಹೆಸರು',
      "first_name": "ಮೊದಲ ಹೆಸರು",
      "last_name": "ಕೊನೆಯ ಹೆಸರು",
      "gender_male": "ಪುರುಷ",
      "gender_female": "ಸ್ತ್ರೀ",
      "dob": "ಜನ್ಮ ದಿನಾಂಕ",
      "age": "ವಯಸ್ಸು",
      "gender": "ಲಿಂಗ",
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      "sub_caste": "ಉಪ ಜಾತಿ",
      "marital_status": "ವೈವಾಹಿಕ ಸ್ಥಿತಿ",
      "creator_name": "ಖಾತೆ ತೆರೆದಿರುವವರು",
      "creator_phone": "ಖಾತೆ ತೆರೆದಿರುವವರ ಫೋನ್ ನಂಬರ್",
      "height": "ಎತ್ತರ (ಸೆಂ.ಮೀ)",
      "weight": "ತೂಕ (ಕೆ.ಜಿ)",
      "blood_group": "ರಕ್ತದ ಗುಂಪು",
      "complexion": "ಬಣ್ಣ",
      "country": "ದೇಶ",
      "state": "ರಾಜ್ಯ",
      "city": "ನಗರ",
      "address": "ವಿಳಾಸ",
      "remarks": "ಅಭಿಪ್ರಾಯಗಳು",
      "qualification": "ಶಿಕ್ಷಣ",
      "specialisation": "ವಿಶೇಷತೆ",
      "profession": "ವೃತ್ತಿ",
      "company_name": "ಕಂಪನಿಯ ಹೆಸರು",
      "company_city": "ಕಂಪನಿಯ ನಗರ",
      "salary_range": "ಸಂಬಳ ಶ್ರೇಣಿ",
      "rashi": "ರಾಶಿ",
      "nakshatra": "ನಕ್ಷತ್ರ",
      "gothra": "ಗೋತ್ರ/ಬೆಡಗು",
      "birth_time": "ಜನ್ಮ ಸಮಯ",
      "birth_place": "ಜನ್ಮ ಸ್ಥಳ",
      "place": "ಸ್ಥಳ",
      "family_deity": "ಕುಲದೇವರು",
      "no_of_kids": "ಮಕ್ಕಳ ಸಂಖ್ಯೆ",
      "father_name": "ತಂದೆಯ ಹೆಸರು",
      "father_occupation": "ತಂದೆಯ ಉದ್ಯೋಗ",
      "mother_name": "ತಾಯಿಯ ಹೆಸರು",
      "mother_occupation": "ತಾಯಿಯ ಉದ್ಯೋಗ",
      "no_of_brothers": "ಸಹೋದರರ ಸಂಖ್ಯೆ",
      "no_of_sisters": "ಸಹೋದರಿಯರ ಸಂಖ್ಯೆ",
      "mother_tongue": "ಮಾತೃಭಾಷೆ",
      "family_type": "ಕುಟುಂಬದ ಪ್ರಕಾರ",
      "reference_name": "ಸೂಚಿಸಿದವರ ಹೆಸರು",
      "reference_phone": "ಸೂಚಿಸಿದವರ ದೂರವಾಣಿ ಸಂಖ್ಯೆ",
      "next": "ಮುಂದೆ",
      "additional_details": "ಹೆಚ್ಚಿನ ವಿವರಗಳು",
      "horoscope": "ಜಾತಕ ವಿವರಗಳು",
      "education_profession": "ಶಿಕ್ಷಣ ಮತ್ತು ವೃತ್ತಿ",
      "family_details": "ಕುಟುಂಬದ ವಿವರಗಳು",
      "permanent_address": "ಶಾಶ್ವತ ವಿಳಾಸ",
      "basic_details": "ಪ್ರಾಥಮಿಕ ವಿವರ",
      "images": "ಚಿತ್ರಗಳು",
      "disabilities": "ಅಂಗವೈಕಲ್ಯ",
      "no_images": "ಯಾವುದೇ ಹೆಚ್ಚುವರಿ ಚಿತ್ರಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
      "liked_by_me": "ನಾನು ಇಷ್ಟಪಟ್ಟವರು",
      "liked_by_others": "ನನ್ನನು ಇಷ್ಟಪಟ್ಟವರು",
      "viewed_by_me": "ನಾನು ವೀಕ್ಷಿಸಿದವರು",
      "viewed_by_others": "ನನ್ನನು ವೀಕ್ಷಿಸಿದವರು",
      "contacted": "ನಾನು ಸಂಪರ್ಕಿಸಿದವರು",
      "mutually_liked": "ಪರಸ್ಪರ ಇಷ್ಟಪಟ್ಟವರು",
      "no_matches": "ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಯ ಪ್ರೊಫೈಲ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
      "submit": "ಸಲ್ಲಿಸಿ",
      "shortlisted": "ಕಿರುಪಟ್ಟಿ",
      "no_profiles": "ಯಾವುದೇ ಪ್ರೊಫೈಲ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
      "category": "ವರ್ಗ",
      "enter_id": "ಮ್ಯಾಟ್ರಿ ಐಡಿ ನಮೂದಿಸಿ",
      "apply_filters": "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ",
      "age_range": "ವಯೋಮಿತಿ: {min} - {max} ವರ್ಷಗಳು",
      "height_range": "ಎತ್ತರ ಶ್ರೇಣಿ: {min} - {max} ಸೆಂ.ಮೀ",
      "matri_id": "ಮ್ಯಾಟ್ರಿ ಐಡಿ",
      "education": "ಶಿಕ್ಷಣ",
      'sign_up': 'ಸೈನ್ ಅಪ್',
      'creating_profile_for': 'ಖಾತೆ ಇವರಿಗಾಗಿ',
      'your_name': 'ನಿಮ್ಮ ಹೆಸರು',
      'get_otp': 'ಒಟಿಪಿ ಉತ್ಪಾದಿಸಿ',
      'enter_otp': 'ಒಟಿಪಿ ನಮೂದಿಸಿ',
      'resend_otp': 'ಒಟಿಪಿ ಪುನಃ ಕಳುಹಿಸಿ',
      'set_password': 'ಪಾಸ್‌ವರ್ಡ್ ಸೆಟ್ ಮಾಡಿ',
      'confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
      'agree': 'ನಾನು ಒಪ್ಪಿಕೊಳ್ಳುತ್ತೇನೆ',
      'terms_and_conditions': ' ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳಿಗೆ',
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
      "otp_resend": "ಒಟಿಪಿ ಪುನಃ ಕಳುಹಿಸಲು {seconds} ಸೆಕೆಂಡುಗಳು ಉಳಿದಿವೆ",
      "enter_personal_details": "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      "enter_sons_details": "ನಿಮ್ಮ ಮಗನ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      "enter_daughters_details": "ನಿಮ್ಮ ಮಗಳ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      "enter_brothers_details": "ನಿಮ್ಮ ಸಹೋದರನ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      "enter_sisters_details": "ನಿಮ್ಮ ಸಹೋದರಿಯ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
      "skip": "ಹಾಗೇ ಬಿಡಿ ಮತ್ತು ಮುಂದುವರಿಸಿ",
      "additional_images": "ಹೆಚ್ಚುವರಿ ಚಿತ್ರಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ",
      "main_image": "ಮುಖ್ಯ ಚಿತ್ರವನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ",
      "partner_preference": "ಸಂಗಾತಿ ಆದ್ಯತೆ",
      "or": "ಅಥವಾ",
      "personal_info": "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
      "contact_info": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
      "contact_details": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
      "block": "ನಿರ್ಬಂಧಿಸಿ",
      "block_report": "ನಿರ್ಬಂಧಿಸಿ ಅಥವಾ ವರದಿ ಮಾಡಿ",
      "cancel": "ರದ್ದುಮಾಡಿ",
      "not_available": "ಲಭ್ಯವಿಲ್ಲ",
      "basic": "ಪ್ರಾಥಮಿಕ",
      "attributes": "ಭೌತಿಕ ಗುಣಲಕ್ಷಣಗಳು",
      "family": "ಕುಟುಂಬ",
      "profile_handler": "ಪ್ರೊಫೈಲ್ ಹ್ಯಾಂಡ್ಲರ್",
      "info": "ಮಾಹಿತಿ",
      "report": "ವರದಿ",
      "reason": "ನಿಮ್ಮ ಕಾರಣವನ್ನು ನಮೂದಿಸಿ",
      "comment":"ಟಿಪ್ಪಣಿ",
      "like":"ಲೈಕ್",
      "confirm_logout":"ಲಾಗ್ಔಟ್ ಅನ್ನು ಖಚಿತಪಡಿಸಿ",
      "confirm_text":"ನೀವು ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?",
      "login_otp":"ಒಟಿಪಿ ಮೂಲಕ ಲಾಗಿನ್ ಮಾಡಿ",
      "login_other":"ಮೊಬೈಲ್ ಸಂಖ್ಯೆ, ಮ್ಯಾಟ್ರಿ ಐಡಿ ಬಳಸಿ ಲಾಗಿನ್ ಮಾಡಿ",
      "forgot_password":"ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರುವಿರಾ",
      "new_account":"ಖಾತೆ ಇರಲಿಲ್ಲವೇ? ಈಗಲೇ ನೋಂದಾಯಿಸಿ",
      "query_support":"ಯಾವುದೇ ಪ್ರಶ್ನೆ / ಬೆಂಬಲಕ್ಕಾಗಿ ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ",
      "change_status":"ಸ್ಥಿತಿಯನ್ನು ಬದಲಾಯಿಸಿ",
      "send_otp":"ಒಟಿಪಿ ಕಳುಹಿಸಿ",
      "verify_otp":"ಒಟಿಪಿ ಪರಿಶೀಲಿಸಿ",
      "confirm_deletion":"ಖಾತೆ ಅಳಿಸುವಿಕೆಯನ್ನು ಖಚಿತಪಡಿಸುವುದೇ?",
      "delete_dialog":"ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಅಳಿಸಲು ನೀವು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?\nಒಮ್ಮೆ ಅಳಿಸಿದ ನಂತರ, ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಮರುಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ ಮತ್ತು ಎಲ್ಲಾ ಡೇಟಾ ಶಾಶ್ವತವಾಗಿ ಕಳೆದುಹೋಗುತ್ತದೆ.",
      "delete":"ಅಕೌಂಟ್ ಅಳಿಸಿ",
      "active":"ಸಕ್ರಿಯ",
      "married":"ವಿವಾಹಿತ",
      "not_interested":"ಆಸಕ್ತಿ ಇಲ್ಲ",
      "exit":"ನಿರ್ಗಮಿಸಿ",
      "confirm_exit":"ನೀವು ನಿರ್ಗಮಿಸಲು ಖಚಿತವಾಗಿ ಬಯಸುವಿರಾ?",
      "no":"ಇಲ್ಲ",
      "no_products":"ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
      "buy":"ಖರೀದಿಸಿ",
      "retry_purchase":"ನೀವು ಖರೀದಿಯನ್ನು ರದ್ದುಗೊಳಿಸಿದಂತೆ ಕಾಣುತ್ತಿದೆ. ನೀವು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಲು ಬಯಸುವಿರಾ?",
      "buy_premium":"ಪ್ರೀಮಿಯಂ ಖರೀದಿಸಿ",
      "need_premium":"ಹೆಚ್ಚಿನ ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ನಿಮಗೆ ಪ್ರೀಮಿಯಂ ಅಗತ್ಯವಿದೆ.",
      "subscribe_now":"ಈಗಲೇ ಚಂದಾದಾರರಾಗಿ",
      "block_user":"ನಿರ್ಬಂಧಿಸಲಾದ ಬಳಕೆದಾರರು ಇನ್ನು ಮುಂದೆ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ವೀಕ್ಷಿಸಲು ಸಾಧ್ಯವಾಗುವುದಿಲ್ಲ.\n",
      "report_user":"ಬಳಕೆದಾರರನ್ನು ಪರಿಶೀಲನೆಗಾಗಿ ನಿರ್ವಾಹಕರಿಗೆ ವರದಿ ಮಾಡಲಾಗುತ್ತದೆ. ಯಾವುದೇ ಕಾನೂನುಬಾಹಿರ ಅಥವಾ ಅನುಚಿತ ವರ್ತನೆಯ ವಿರುದ್ಧ ಕಠಿಣ ಕ್ರಮ ಕೈಗೊಳ್ಳಲಾಗುತ್ತದೆ ಮತ್ತು ಬಳಕೆದಾರರು ಇನ್ನು ಮುಂದೆ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ವೀಕ್ಷಿಸಲು ಸಾಧ್ಯವಾಗುವುದಿಲ್ಲ.",
      "no_message":"ಯಾವುದೇ ಸಂದೇಶವಿಲ್ಲ",
      "type_message":"ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ....",
      "fill_info":"ದಯವಿಟ್ಟು ಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಸರಿಯಾಗಿ ಭರ್ತಿ ಮಾಡಿ.",
      "ok":"ಸರಿ",
      "reset_password":"ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
      "success":"ಯಶಸ್ಸು",
      "failed":"ವಿಫಲವಾಯಿತು",
      "success_msg":"ಟಿಕೆಟ್ ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ.",
      "failure_msg":"ಟಿಕೆಟ್ ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.",
      "support":"ಬೆಂಬಲ",
      "issues":"ಸಮಸ್ಯೆಗಳು",
      "min_char":"(ಕನಿಷ್ಠ 10 ಅಕ್ಷರಗಳು)",
      "support_contact":"ಬೆಂಬಲ/ಸಂಪರ್ಕ",
      "taralabalu":"ತರಳಬಾಳು ಕೇಂದ್ರ",
      "phone":"ದೂರವಾಣಿ:",
      "tb_address":"ವಿಳಾಸ: 2ನೇ ಬ್ಲಾಕ್, 3ನೇ ಮುಖ್ಯರಸ್ತೆ, ಬಿಡಿಎ ಕಾಂಪ್ಲೆಕ್ಸ್ ಹತ್ತಿರ, \nಆರ್‌ಟಿ ನಗರ, ಬೆಂಗಳೂರು, ಕರ್ನಾಟಕ 560032",
      "contact_us":"ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ",
      "upload_profile":"ಪ್ರೊಫೈಲ್ ಅನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ",
      "profile_msg":"ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಚಿತ್ರವನ್ನು ನವೀಕರಿಸಿ.",
      "upload_now":"ಈಗ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
      "login_validation":"ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಐಡಿ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.",
      "accept_terms":"ಮುಂದುವರಿಯಲು ದಯವಿಟ್ಟು ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಒಪ್ಪಿಕೊಳ್ಳಿ.",
      "no_internet":"ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿಲ್ಲ",
      "no_internet_msg":"ದಯವಿಟ್ಟು ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್ ಪರಿಶೀಲಿಸಿ ಹಾಗೂ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
      "new_password":"ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
      "change_password":"ಪಾಸ್‌ವರ್ಡ್ ಬದಲಾಯಿಸಿ",
      "choose":"ಒಂದು ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ:",
      "set_profile":"ಪ್ರೊಫೈಲ್ ಫೋಟೋವಾಗಿ ಹೊಂದಿಸಿ",
      "delete_photo":"ಫೋಟೋ ಅಳಿಸಿ",
      "upload_one":"ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಒಂದು ಚಿತ್ರವನ್ನಾದರೂ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
      "no_chats":"ಯಾವುದೇ ಚಾಟ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ",
      "profile_count":"ಬಾಕಿ ಉಳಿದಿರುವ ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಣೆ ಸಂಖ್ಯೆ",
      "message_count":"ಬಾಕಿ ಉಳಿದಿರುವ ಸಂದೇಶ ಸಂಖ್ಯೆ",
      "contact_count":"ಬಾಕಿ ಉಳಿದಿರುವ ಸಂಪರ್ಕಗಳ ಸಂಖ್ಯೆ",
      "pending_counts":"ಬಾಕಿಯಿರುವ ಸಂಖ್ಯೆಗಳು"
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]![key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'kn'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate old) => false;
}
